### ISSUE TITLE
KeyError from txAWS while reporting another error

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#128]
```

[Failure instance: Traceback: <class 'txaws.ec2.exception.EC2Error'>: <EC2Error instance at 0x8df94dc with str error:
 Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 546, in _safeFormat
    return formatter(o)
  File "/usr/local/lib/python2.7/dist-packages/txAWS-0.2.1.post4-py2.7.egg/txaws/exception.py", line 24, in __str__
    return self._get_error_message_string()
  File "/usr/local/lib/python2.7/dist-packages/txAWS-0.2.1.post4-py2.7.egg/txaws/exception.py", line 54, in _get_error_message_string
    error_message = self.get_error_messages()
  File "/usr/local/lib/python2.7/dist-packages/txAWS-0.2.1.post4-py2.7.egg/txaws/exception.py", line 122, in get_error_messages
    return self.errors[0]["Message"]
KeyError: 'Message'
>
/usr/lib/python2.7/dist-packages/twisted/protocols/policies.py:123:connectionLost
/usr/lib/python2.7/dist-packages/twisted/web/client.py:191:connectionLost
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:362:callback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:458:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:545:_runCallbacks
/usr/local/lib/python2.7/dist-packages/txAWS-0.2.1.post4-py2.7.egg/txaws/ec2/client.py:23:ec2_error_wrapper
/usr/local/lib/python2.7/dist-packages/txAWS-0.2.1.post4-py2.7.egg/txaws/client/base.py:46:error_wrapper
]
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>Unavailable</Code><Message>The service is unavailable. Please try again shortly.</Message></Error></Errors><RequestID>f5060c54-dcc7-4503-9d14-ad6472fb55b2</RequestID></Response>
```

Notice that the underlying error is somewhat obscured by a type error in the `get_error_messages()` method in `txaws/exception.py`. (We get the message from AWS anyway, which in this case happens to be sufficient to tell what happened, but we don't get the underlying error's traceback.)

**Comment by exarkun** [comment]
We're not using txAWS EC2 client anymore so we don't need a fix for this.
