### ISSUE TITLE
update_testing_leastauthority_repo.py fails due to needing to prompt for a password

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#293]
```
$ python ./update_testing_leastauthority_repo.py
a76b448029f7e94c463284bcd9e7945ad0206ccc
[website@testing.leastauthority.com] run: whoami

Fatal error: Needed to prompt for a connection or sudo password (host: website@testing.leastauthority.com), but abort-on-prompts was set to True

Aborting.
Traceback (most recent call last):
  File "./update_testing_leastauthority_repo.py", line 43, in <module>
    leastauthority_commit_ref, admin_privkey_path))
  File "/home/davidsarah/tahoe/git/LeastAuthority/leastauthority.com/lae_automation/server.py", line 409, in update_leastauthority_repo
    set_host_and_key(publichost, admin_privkey_path, 'website')
  File "/home/davidsarah/tahoe/git/LeastAuthority/leastauthority.com/lae_automation/server.py", line 175, in set_host_and_key
    raise NotListeningError()
lae_automation.server.NotListeningError
```

**Comment by exarkun** [comment]
Infrastructure servers now deployed with Kubernetes, this is no longer relevant.
