### ISSUE TITLE
Separate monitoring packaging so that we don't need rho/phi dependencies.

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#305]
Currently the `lae_*` modules transitively import stuff used in different contexts.  For example, on `analytics` just now where we were attempting to deploy monitoring we see:

```
analytics@ip-10-204-239-9:~$ cd leastauthority.com/
analytics@ip-10-204-239-9:~/leastauthority.com$ ./website_check.sh
Traceback (most recent call last):
  File "website_check.py", line 7, in <module>
    from lae_automation.monitor import check_infrastructure, monitoring_check
  File "/home/analytics/leastauthority.com/lae_automation/monitor.py", line 15, in <module>
    from lae_automation.aws.queryapi import pubIPextractor
  File "/home/analytics/leastauthority.com/lae_automation/aws/queryapi.py", line 8, in <module>
    from txaws.util import XML
ImportError: No module named txaws.util
```

Monitoring code doesn't actually depend on `txaws` or `fabric` or various other things.

**Comment by exarkun** [comment]
The entire monitoring system fell over a long time ago, unfortunately. We have a "Monitoring and Reporting" milestone. We'll put plans for future work there.
