### ISSUE TITLE
nondeterministic or timing-related failure when running update_testing_blog.py

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#314]
```
$ python update_testing_blog.py
5786128dea41d5b8a3cfd6073ff9f06f88a1c698
[website@testing.leastauthority.com] run: whoami
[website@testing.leastauthority.com] out: website
[website@testing.leastauthority.com] out: 

error: dst refspec 2014-09-03T23-50-53Z_testing.leastauthority.com_5786128d matches more than one.
error: failed to push some refs to 'website@testing.leastauthority.com:/home/website/blog_source/'
Traceback (most recent call last):
  File "update_testing_blog.py", line 14, in <module>
    stdout=sys.stdout)
  File "/home/davidsarah/tahoe/git/LeastAuthority/leastauthority.com/lae_automation/server.py", line 459, in check_branch_and_update_blog
    update_blog(host, blog_repo_path, blog_commit_ref, admin_privkey_path)
  File "/home/davidsarah/tahoe/git/LeastAuthority/leastauthority.com/lae_automation/server.py", line 442, in update_blog
    admin_privkey_path)
  File "/home/davidsarah/tahoe/git/LeastAuthority/leastauthority.com/lae_automation/server.py", line 326, in tag_push_checkout
    subprocess.check_call(local_git_push, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/git', '--git-dir=../blog_source/.git', 'push', 'website@testing.leastauthority.com:/home/website/blog_source/', '2014-09-03T23-50-53Z_testing.leastauthority.com_5786128d:2014-09-03T23-50-53Z_testing.leastauthority.com_5786128d']' returned non-zero exit status 1
```

It succeeded when I ran the same command again.

**Comment by exarkun** [comment]
The new blog will have a completely different and (hopefully) better update process.
