### ISSUE TITLE
Error reporting bug in failed signup

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#340]
The relevant part of the signup log is:

```
...
>The server's public address is '54.165.234.253'.>
>Attempting to get console data. Will try for 600 seconds.>
[Failure instance: Traceback: <class 'txaws.ec2.exception.EC2Error'>: <EC2Error instance at 0x7f97a15f0e10 with str error:
 Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/_reflectpy3.py", line 354, in _safeFormat
    return formatter(o)
  File "build/bdist.linux-x86_64/egg/txaws/exception.py", line 24, in __str__
    return self._get_error_message_string()
  File "build/bdist.linux-x86_64/egg/txaws/exception.py", line 54, in _get_error_message_string
    error_message = self.get_error_messages()
  File "build/bdist.linux-x86_64/egg/txaws/exception.py", line 122, in get_error_messages
    return self.errors[0]["Message"]
KeyError: 'Message'
>
/usr/lib/python2.7/dist-packages/twisted/protocols/policies.py:125:connectionLost
/usr/lib/python2.7/dist-packages/twisted/web/client.py:204:connectionLost
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:382:callback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:490:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:577:_runCallbacks
build/bdist.linux-x86_64/egg/txaws/ec2/client.py:23:ec2_error_wrapper
build/bdist.linux-x86_64/egg/txaws/client/base.py:46:error_wrapper
]
>Failure notification email sent to support@leastauthority.com.>
```

**Comment by exarkun** [comment]
Switching to container-based signup so this will go away because we won't be doing EC2 calls in signup.
