### ISSUE TITLE
include e-mail in signup failure reporting

### ISSUE THREAD

**Issue by david415** [LeastAuthority/leastauthority.com#364]
If these signup errors had customer contact info such as their name and e-mail then we could contact them... asking if they'd try their signup again. We'd likely get more customers if we did this. It might also help us understand the signup bugs and fix them.

Note: This error could be caused by insufficient funds, or other charge-disabling factors related to the User's payment credential.

```
Traceback (most recent call last):
File "/home/website/leastauthority.com/lae_site/handlers/submit_subscription.py", line 71, in create_customer
email=user_email)
File "/usr/local/lib/python2.7/dist-packages/stripe/resource.py", line 269, in create
response, api_key = requestor.request('post', url, params)
File "/usr/local/lib/python2.7/dist-packages/stripe/api_requestor.py", line 130, in request
resp = self.interpret_response(rbody, rcode)
File "/usr/local/lib/python2.7/dist-packages/stripe/api_requestor.py", line 234, in interpret_response
self.handle_api_error(rbody, rcode, resp)
File "/usr/local/lib/python2.7/dist-packages/stripe/api_requestor.py", line 150, in handle_api_error
err.get('code'), rbody, rcode, resp)
CardError: Your card was declined.
```

**Comment by Liz315** [comment]
This may be resolved by our improvements. For this, we need to address the error reporting with Stripe and operational error reporting to notify customers about their failed signup.
