### ISSUE TITLE
Sometimes storage servers become unusable

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/leastauthority.com#691]
Several storage servers have recently entered a state where connection attempts to them hang, seemingly indefinitely.

After some investigation, I've found that:

On the server, a traceback like the following appears in the flog:

```
19:33:50.467 L23 []#1293 an inbound callRemote that we [i5xb] executed (on behalf of someone else, TubID vvl5) failed                                                                                              
19:33:50.467 L10 []#1294  reqID=1, rref=<foolscap.broker.Broker object at 0x7f3c462ffa50>, methname=RIBroker.getReferenceByName                                                                                    
19:33:50.467 L10 []#1295  args=[]                   
19:33:50.467 L10 []#1296  kwargs={'name': '44...'}                            
19:33:50.467 L10 []#1297  the LOCAL failure was:    
 FAILURE:                                                                                                
 [CopiedFailure instance: Traceback from remote host -- Traceback (most recent call last):               
   File "/app/env/local/lib/python2.7/site-packages/foolscap/eventual.py", line 26, in _turn             
     cb(*args, **kwargs)
   File "/app/env/local/lib/python2.7/site-packages/foolscap/broker.py", line 579, in doNextCall
     d.addCallback(lambda res: self._doCall(delivery))
   File "/app/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
     callbackKeywords=kw)
   File "/app/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
     self._runCallbacks()
 --- <exception caught here> ---
   File "/app/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
     current.result = callback(current.result, *args, **kw)
   File "/app/env/local/lib/python2.7/site-packages/foolscap/broker.py", line 579, in <lambda>
     d.addCallback(lambda res: self._doCall(delivery))
   File "/app/env/local/lib/python2.7/site-packages/foolscap/broker.py", line 614, in _doCall
     return obj.doRemoteCall(delivery.methodname, args, kwargs)
   File "/app/env/local/lib/python2.7/site-packages/foolscap/referenceable.py", line 59, in doRemoteCall
     res = meth(*args, **kwargs)
   File "/app/env/local/lib/python2.7/site-packages/foolscap/broker.py", line 495, in remote_getReferenceByName
     return self.tub.getReferenceForName(name)
   File "/app/env/local/lib/python2.7/site-packages/foolscap/pb.py", line 708, in getReferenceForName
     % hint)
 exceptions.KeyError: "unable to find reference for name starting with '44'"
```

The name requested is the reference identifier included in the fURL announced by the introducer.

Note that these storage servers appear to start in a working state and then transition to a broken state.

Also, I've observed that the BASEDIR/private/storage.furl path, which is supposed to contain the storage server fURL, contains a fURL with an entirely different swissnum (reasons unknown).

**Comment by exarkun** [comment]
fwiw, the server flog can be inspected via:

    /app/env/bin/flogtool tail /var/run/storageserver/private/logport.furl

**Comment by exarkun** [comment]
After inspecting the corresponding _introducer_ flog, I discovered an error logged there indicating the introducer was rejecting new storage server announcements because of invalid sequence numbers.  Indeed, our storage servers have their announcement sequence number reset to 1 on each restart.  This is not allowed by the introducer.
